parameters:
  - name: qaRepoRef
    type: string
steps:
  # Checkout repo
  - checkout: 'git://Repo@${{ parameters.qaRepoRef }}'
    displayName: 'Checkout Repo'
    path: path
  # Install Node.js
  - task: NodeTool@0
    displayName: "Install Node.js"
    inputs:
      versionSpec: "18.x"
  # Install NPM dependencies
  - task: Npm@1
    displayName: "Install NPM dependencies"
    inputs:
      workingDir: "$(Agent.BuildDirectory)/path"
      command: "ci"
  # Install Ubuntu Dependencies
  - script: |
      set -ev
      sudo apt-get update
      sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
    displayName: "Install Ubuntu Dependencies"
    workingDirectory: "$(Agent.BuildDirectory)/path"
  # Run tests
  - script: |
      set -ev
      npm run cypress:execution-report
    displayName: "Run tests and generate coverage report"
    workingDirectory: "$(Agent.BuildDirectory)/path"
